version: '3'
services:
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
#    networks:
#      - my-network

  pgadmin:
    image: dpage/pgadmin4:4
    ports:
      - '88:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hairun-technology.com
      PGADMIN_DEFAULT_PASSWORD: admin
#    networks:
#      - my-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: yesboss
      POSTGRES_USER: yesboss
    ports:
      - '5432:5432'
#    networks:
#      - my-network

  graphql:
    build:
      context: server/graphql
      dockerfile: dev.Dockerfile
    image: yesboss-server
#    networks:
#      - my-network
    ports:
      - '4000:4000'
      - '9229:9229'
      - '4002:4002'
    volumes:
      - ./server/graphql/src:/graphql/src
      - ./server/graphql/dist:/graphql/dist
      - ./server/graphql/services-accounts.json:/graphql/service-account-file.json
    depends_on:
      - postgres
      - redis
    env_file:
      - ./server/graphql/.env.dev
#networks:
#  my-network:
#    driver: bridge